### ISSUE TITLE
 the packaged program cannot start or flash back

### ISSUE THREAD

**Issue by wo2350405615** [RLoris/SocketHelperDoc#2] opened 2021-08-11 09:45 UTC
When I enable this plug-in, the packaged program cannot start or flash back, even if it does not use any nodes in the blueprint. I hope to get the correct usage and cases of your plug-in.

**Comment by RLoris** [comment] 2021-08-11 09:51
Hello @wo2350405615, thanks for reaching me, can you send me more informations about what you are trying to accomplish ? like a blueprint graph, or logs of the error ? This will be easier for me

**Comment by wo2350405615** [comment] 2021-08-11 10:01
LogPlayLevel: ********** STAGE COMMAND COMPLETED **********
LogPlayLevel: ********** PACKAGE COMMAND STARTED **********
LogPlayLevel: ********** PACKAGE COMMAND COMPLETED **********
LogPlayLevel: ********** DEPLOY COMMAND STARTED **********
LogPlayLevel: Warning: WARNING: Win64 does not implement Deploy...
LogPlayLevel: ********** DEPLOY COMMAND COMPLETED **********
LogPlayLevel: ********** RUN COMMAND STARTED **********
LogPlayLevel: Starting Client....
LogPlayLevel: Completed Launch On Stage: Deploy Task, Time: 1.502253
LogPlayLevel: Running: D:\Documents\Unreal Projects\UDP\Saved\StagedBuilds\WindowsNoEditor\UDP\Binaries\Win64\UDP.exe ../../../UDP/UDP.uproject /Game/UDP/UDP -stdout -abslog="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+xvhuan4+UE_4.26\Client.log" -Messaging -Windowed -CrashForUAT -SessionId=E01F5F6E4BB6B6631D573BBAD0EFEA95 -Ses
sionOwner="Administrator" -SessionName="Launch On Device"
LogPlayLevel: Error: **![QQ](https://user-images.githubusercontent.com/67098417/129010180-58de91fe-34bb-4ce2-8528-096bb9869c6d.png)
LogPlayLevel:        (see C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+xvhuan4+UE_4.26\Log.txt for full exception trace)
LogPlayLevel: AutomationTool exiting with ExitCode=1 (Error_Unknown)
LogPlayLevel: Completed Launch On Stage: Run Task, Time: 5.510105

**Comment by wo2350405615** [comment] 2021-08-11 10:03
When I enable the plug-in, the packaged program cannot start or flash back. When I close the plug-in, the packaged program can start normally

**Comment by RLoris** [comment] 2021-08-11 10:06
I will look into this and try to package to see if I get the error

**Comment by RLoris** [comment] 2021-08-11 10:15
I don't have any problem packaging a build on my side with the plugin enabled: 

![buildsocketwin64](https://user-images.githubusercontent.com/47107767/129011975-22b847ca-d2af-483b-b17f-ae1192dba560.PNG)

I will look more into your error... to try to find a solution for you

**Comment by wo2350405615** [comment] 2021-08-11 10:20
![Uploading 无法启动1.png…]()


Unable to start

**Comment by wo2350405615** [comment] 2021-08-11 10:21
![Uploading 1.png…]()

**Comment by RLoris** [comment] 2021-08-11 10:22
Can you send me the full log ? The file can be found just below the error code in red, where it says "see C:\users\Administrator\AppData\Roaming\Unreal Engine\Automation..."

**Comment by wo2350405615** [comment] 2021-08-11 10:22
Maybe it's my own problem. I'll think of a way myself

**Comment by RLoris** [comment] 2021-08-11 10:24
If you send me your log file with the error, I can have a look and try to understand where the issue comes from ? 

> Can you send me the full log ? The file can be found just below the error code in red, where it says "see C:\users\Administrator\AppData\Roaming\Unreal Engine\Automation..."

**Comment by wo2350405615** [comment] 2021-08-11 10:26
[FinalCopy_NonUFSFiles.txt](https://github.com/RLoris/SocketHelperDoc/files/6967606/FinalCopy_NonUFSFiles.txt)
[FinalCopy_NonUFSFilesDebug.txt](https://github.com/RLoris/SocketHelperDoc/files/6967607/FinalCopy_NonUFSFilesDebug.txt)
[FinalCopy_UFSFiles.txt](https://github.com/RLoris/SocketHelperDoc/files/6967608/FinalCopy_UFSFiles.txt)
[Log.txt](https://github.com/RLoris/SocketHelperDoc/files/6967609/Log.txt)
[Manifest_NonUFSFiles_Win64.txt](https://github.com/RLoris/SocketHelperDoc/files/6967610/Manifest_NonUFSFiles_Win64.txt)
[UnrealPak-UDP-WindowsNoEditor-2021.08.11-18.16.51.txt](https://github.com/RLoris/SocketHelperDoc/files/6967611/UnrealPak-UDP-WindowsNoEditor-2021.08.11-18.16.51.txt)
[PakList_UDP-WindowsNoEditor.txt](https://github.com/RLoris/SocketHelperDoc/files/6967613/PakList_UDP-WindowsNoEditor.txt)
[PrePak_WindowsNoEditor_NonUFSFiles.txt](https://github.com/RLoris/SocketHelperDoc/files/6967615/PrePak_WindowsNoEditor_NonUFSFiles.txt)
[PrePak_WindowsNoEditor_NonUFSFilesDebug.txt](https://github.com/RLoris/SocketHelperDoc/files/6967617/PrePak_WindowsNoEditor_NonUFSFilesDebug.txt)
[PrePak_WindowsNoEditor_UFSFiles.txt](https://github.com/RLoris/SocketHelperDoc/files/6967618/PrePak_WindowsNoEditor_UFSFiles.txt)
[Cook-2021.08.11-18.16.50.txt](https://github.com/RLoris/SocketHelperDoc/files/6967620/Cook-2021.08.11-18.16.50.txt)
[UBT-UDP-Win64-Development.txt](https://github.com/RLoris/SocketHelperDoc/files/6967621/UBT-UDP-Win64-Development.txt)
I don't know which file it is. Can you help me

**Comment by RLoris** [comment] 2021-08-11 10:28
The one located at this full path under the error in your logs : 

![errorlogfile](https://user-images.githubusercontent.com/47107767/129013841-b1c92abd-2aed-4ea7-aff9-c80fa6661a77.PNG)

**Comment by wo2350405615** [comment] 2021-08-11 10:35
[Log.txt](https://github.com/RLoris/SocketHelperDoc/files/6967708/Log.txt)

**Comment by RLoris** [comment] 2021-08-11 10:53
Thanks, the warning "win64 does not implement deploy" should not appear! I think the problem is located in the config of your engine, can you send me the DefaultEngine.ini located in <your_project_folder>/Config/DefaultEngine.ini ?

**Comment by wo2350405615** [comment] 2021-08-11 11:18
Sorry, I'll send it to you tomorrow. Now I have other things to deal with.

**Comment by RLoris** [comment] 2021-08-11 20:46
Hey @wo2350405615 the new version is now live, you can restart the launcher and update the plugin, tell me if your issue is solved when building and running your game ?

**Comment by wo2350405615** [comment] 2021-08-13 03:32
No problem,

**Comment by RLoris** [comment] 2021-08-13 08:16
Perfect, I'm closing this issue since it's resolved !

**Closed** 2021-08-13 08:16 UTC
